[project]
# Support Python 3.10+.
requires-python = ">=3.10"

[tool.ruff]
line-length = 120
include = ["frontend/**/*.(py|pyi)", "backend/**/*.(py|pyi)", "**/pyproject.toml"]

[tool.ruff.lint]
select = ["D102", "F401"]

[tool.ruff.lint.isort]
case-sensitive = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pylint]
max-line-length = 120

[tool.mypy]
ignore_missing_imports = false
